# Generated by Django 4.2.7 on 2023-11-23 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='caracteristicas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
